version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    # Limit to 0 to enable only security updates:
    open-pull-requests-limit: 0
    reviewers:
      - artsy/onyx-devs
