---
version: "2"
services:
  convection:
    env_file: ../.env
{% include 'templates/docker-compose-service.yml.j2' %}
    ports:
      - 3000:3000
    volumes:
      - ../:/app
    depends_on:
      - convection-postgres
  convection-postgres:
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
