---
version: "2"
services:
  convection:
    command: ./hokusai/ci.sh
    environment:
      - RAILS_ENV=test
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
      - DATABASE_URL=postgresql://postgres:@convection-postgres/convection_test
{% include 'templates/docker-compose-service.yml.j2' %}
    depends_on:
      - convection-postgres
  convection-postgres:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=convection_test
      - POSTGRES_HOST_AUTH_METHOD=trust
